name: Scala CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run build
      run: ./build.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'pages'
          fetch-depth: 0
      - name: update branch
        run: |
          git config --global user.name '${{ github.event.pusher.name }}'
          git config --global user.email '${{ github.event.pusher.email }}'
          git status
          git fetch
          git pull -r
          git branch -v -a
          echo 'rebase'
          git rebase -v origin/main
          git rebase --skip
          ./run.sh
          echo 'add'
          git add ./docs/.
          echo 'commit'
          git commit -m "update docs"
          echo 'push'
          git push -f
